language: minimal
addons:
  apt:
    sources:
    - sourceline: 'ppa:brightbox/ruby-ng'
    packages:
    - ruby2.4
    - ruby2.4-dev
    update: true
install:
  - sudo gem pristine --all
  - sudo gem install sqlint
script:
  - sqlint *.sql